#! /bin/sh

sxhkd &

sudo localedef -f UTF-8 -i en_US en_US.UTF-8

# Set environment
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"
bspc monitor -d term brwsr chat video code VI VII VIII IX X

# Gaps, padding, and size
bspc config border_width 2
bspc config window_gap 5
bspc config split_ratio         1
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config single_monocle      true
bspc config history_aware_focus true
#bspc config swallow_first_click true
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config initial_polarity second_child


# Border colors
bspc config presel_feedback_color "#ebdbb2"
bspc config normal_border_color "#928374"
bspc config focused_border_color "#ebdbb2"
bspc config focus_follows_pointer false

# Resize and move windows with mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config click_to_focus any

# Window rules

bspc rule -a scratchterm sticky=on state=floating hidden=on
bspc rule -a Zathura state=tiled
bspc rule -a Grsync state=tiled

#bspc rule -a discord desktop='^5' follow=off
#bspc rule -a Code desktop='^1' follow=off
#bspc rule -a Subl3 desktop='^1' follow=off
#bspc rule -a Chromium desktop='^3' follow=off

# Autostart
#"$BSPWM_CONFIG/floating.sh" &
"$BSPWM_CONFIG/autostart" &
